#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

list_versions() {
  gem list "^$gem_name\$" --remote --all $(source_option) $(prerelease_option) | \
    cut -d '(' -f2 | \
    cut -d ')' -f1 | \
    tr ',' '\n' | \
    awk '{print $1}'
}

latest_version() {
  list_versions | head -1
}

payload=$(mktemp /tmp/rubygems.XXXXXX)
cat > $payload <&0

gem_name=$(attr source gem_name)
version_number=$(jq -r '.version.number // ""' < $payload)

configure_credentials

if [ -z "$version_number" ]; then
  list_versions | jq -R '.' | jq -s "map({number: .})" >&3
else
  latest_version | jq -R '.' | jq -s "map({number: .})" >&3
fi
